apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark
  # SparkOperator creates a service account in default namespace
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: 153931337802.dkr.ecr.us-west-2.amazonaws.com/sagemaker-spark-processing:3.5-cpu-py39-v1.0
  imagePullPolicy: Always
  #mainApplicationFile: local:///opt/spark/spark-example.py
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.5.0"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.5.0
    serviceAccount: so-spark-operator-spark
  executor:
    #cores: 2
    instances: 2
    memory: "512m"
    # template:
    #   labels:
    #     version: 3.5.0
    #   spec:
    #     containers:
    #     - name: spark-kubernetes-executor
    #       volumeMounts:
    #       - name: spark-script
    #         mountPath: /opt/spark/spark-example.py
    #       volumes:
    #       - name: spark-script
    #         configMap:
    #         name: sparkscript

