prometheus:
  prometheusSpec:
    retention: 5h
    scrapeInterval: 30s
    evaluationInterval: 30s
    scrapeTimeout: 10s
    serviceMonitorSelectorNilUsesHelmValues: false # This is required to use the serviceMonitorSelector
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          storageClassName: gp3
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 50Gi
alertmanager:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: mlops-grafana-pwd
