apiVersion: apps/v1
kind: Deployment
metadata:
 name: chatbot
 labels:
   app: chatbot
spec:
 replicas: 1
 selector:
   matchLabels:
     app: chatbot
 template:
   metadata:
     labels:
       app: chatbot
   spec:
     containers:
     - name: chatbot
       image: pytorch/pytorch:2.5.1-cuda12.1-cudnn9-runtime
       command: ["/bin/sleep", "infinity"]
       resources:
         limits:
           nvidia.com/gpu: 1
       ports:
       - containerPort: 7860
       volumeMounts:
         - mountPath: /dev/shm
           name: dshm
     volumes:
     - emptyDir:
         sizeLimit: 1Gi
         medium: Memory
       name: dshm
