apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: modern-engg
  sources:
    - chart: aws-load-balancer-controller
      repoURL: https://aws.github.io/eks-charts
      targetRevision: 1.9.0
      helm:
        releaseName: aws-load-balancer-controller
        parameters:
          - name: serviceAccount.name
            value: aws-load-balancer-controller
          - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
            value: ${MGMT_ROLE_ARN}
          - name: clusterName
            value: ${CLUSTER_NAME}
          - name: vpcId
            value: ${EKS_VPC_ID}
          - name: region
            value: ${EKS_REGION}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: aws-load-balancer-controller
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: aws-load-balancer-webhook
      namespace: aws-load-balancer-controller
      jsonPointers:
        - /data
    - group: "admissionregistration.k8s.io"
      kind: MutatingWebhookConfiguration
      name: aws-load-balancer-webhook
      namespace: aws-load-balancer-controller
      jsonPointers:
        - /webhooks[]/clientConfig/caBundle
    - group: "admissionregistration.k8s.io"
      kind: ValidatingWebhookConfiguration
      name: aws-load-balancer-webhook
      namespace: aws-load-balancer-controller
      jsonPointers:
        - /webhooks[]/clientConfig/caBundle
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true