apiVersion: v1
kind: Pod
metadata:
  name: sleep-pod
spec:
  containers:
  - name: sleep-container
    image: ubuntu:22.04
    command: ["/bin/sleep", "infinity"]
    #command: ["/bin/sh", "-c"]
    #args: ["while true; do sleep 30; done"]
