---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: g5-gpu-karpenter
spec:
  amiFamily: Bottlerocket
  role: "machine-learning"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 300Gi
        volumeType: gp3
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: machine-learning
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: machine-learning
  tags:
    karpenter.sh/discovery: machine-learning
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: x86-cpu-karpenter-br
spec:
  amiFamily: Bottlerocket
  role: "machine-learning"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 300Gi
        volumeType: gp3
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: machine-learning
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: machine-learning
  tags:
    karpenter.sh/discovery: machine-learning
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: x86-cpu-karpenter-br
spec:
  template:
    metadata:
      labels:
        type: karpenter
        NodeGroupType: x86-cpu-karpenter-br
    spec:
      nodeClassRef:
        name: x86-cpu-karpenter-br
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["m5"]
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values: [ "xlarge", "2xlarge", "4xlarge", "8xlarge"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand", "spot"]
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 300s
    expireAfter: 720h
  weight: 100
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: g5-gpu-karpenter
spec:
  template:
    metadata:
      labels:
        type: karpenter
        NodeGroupType: g5-gpu-karpenter
    spec:
      nodeClassRef:
        name: g5-gpu-karpenter
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["g5"]
        - key: "karpenter.k8s.aws/instance-size"
          operator: In
          values: [ "2xlarge", "4xlarge", "8xlarge" ]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand"]
      taints:
        - key: nvidia.com/gpu
          effect: NoSchedule
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 300s
    expireAfter: 720h
  weight: 100