{
 "title": "Neuron / Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Instance Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "instance{job=\"kubernetes-service-endpoints\"}"
    }
   ]
  },
  {
   "title": "Instance Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(instance{job=\"kubernetes-service-endpoints\"})\n"
    }
   ]
  },
  {
   "title": "vCPU Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum (system_vcpu_count)" }
   ]
  },
  {
   "title": "vCPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance_id) (system_vcpu_usage_ratio))"
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(system_memory_used_bytes / system_memory_total_bytes)"
    }
   ]
  },
  {
   "title": "NeuronCores in Use",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(neuroncore_utilization_ratio > 0)"
    }
   ]
  },
  {
   "title": "NeuronCore Utilization",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(neuroncore_utilization_ratio)"
    }
   ]
  },
  {
   "title": "Execution Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(execution_status_total{status_type=\"completed\"}[1m]))"
    }
   ]
  },
  {
   "title": "Execution Error Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(execution_status_total{status_type!=\"completed\"}[1m]))"
    }
   ]
  },
  {
   "title": "Execution Status Rates",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(execution_status_total{status_type=\"completed\"}[1m]))",
     "legendFormat": "Execution Success Rate"
    },
    {
     "expr": "sum(rate(execution_status_total{status_type!=\"completed\"}[1m]))",
     "legendFormat": "Execution Error Rate"
    }
   ]
  },
  {
   "title": "Execution Latency",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg by (percentile) (execution_latency_seconds)",
     "legendFormat": "{{percentile}}"
    }
   ]
  },
  {
   "title": "NeuronCore Utilization",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (neuroncore) (neuroncore_utilization_ratio)",
     "legendFormat": "nc{{neuroncore}}"
    }
   ]
  },
  {
   "title": "Neuron Runtime vCPU Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (usage_type) (neuron_runtime_vcpu_usage_ratio)",
     "legendFormat": "Neuron Runtime {{usage_type}} CPU usage "
    }
   ]
  },
  {
   "title": "Neuron Runtime Used Memory",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (memory_location) (sum by (instance_id, memory_location) (neuron_runtime_memory_used_bytes))",
     "legendFormat": "{{memory_location}}"
    }
   ]
  },
  {
   "title": "Host System Utilization",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(system_memory_used_bytes / system_memory_total_bytes)",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "avg(sum by (instance_id) (system_vcpu_usage_ratio))",
     "legendFormat": "vCPU Usage"
    },
    {
     "expr": "avg(neuroncore_utilization_ratio)",
     "legendFormat": "NeuronCore Usage"
    }
   ]
  },
  {
   "title": "Host vCPU Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (usage_type) (system_vcpu_usage_ratio)",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(system_memory_used_bytes / system_memory_total_bytes)",
     "legendFormat": "Memory Usage Percent"
    },
    { "expr": "avg(system_memory_used_bytes)", "legendFormat": "Memory Usage Bytes" }
   ]
  }
 ]
}